__default__:
    queue: fast
    ncpus: 1
    mem: 16G
    ntasks: 1
    partition : common,dedicated
    name: T7.{rule}.{wildcards}
    output: logs/cluster/{rule}.{wildcards}.out
    error: logs/cluster/{rule}.{wildcards}.err

split_fastq:
    queue: normal
    partition: common
    ncpus: 8
    mem: 16G
    ntasks: 1
    name: T7.{rule}.{wildcards}
    output: logs/cluster/{rule}.{wildcards}.out
    error: logs/cluster/{rule}.{wildcards}.err

split_fastq_se:
    queue: normal
    partition: common
    ncpus: 8
    mem: 16G
    ntasks: 1
    name: T7.{rule}.{wildcards}
    output: logs/cluster/{rule}.{wildcards}.out
    error: logs/cluster/{rule}.{wildcards}.err


# Command to run everything

# First it's necessary to build conda env as the cluster nodes are not connected
# to the network.
# snakemake --conda-create-envs-only --use-conda -j 1

# Build the log directory.
# mkdir -p logs/cluster/

# Run everything on cluster.
# snakemake --cluster "sbatch --mem {cluster.mem} -p {cluster.partition} --qos {cluster.queue} -c {cluster.ncpus} -n {cluster.ntasks} -J {cluster.name} -o {cluster.output} -e {cluster.error}" --cluster-config config/cluster_slurm.yaml -j 64 --use-conda