samples: "config/samples.csv"
base_dir: "/home/sardine/Documents/"
out_dir: "/home/sardine/Bureau/results"
ref_dir: "genomes/"
fastq_dir: "reads/"

threads: 64
threads_small: 32
threads_big : 128

# Alignment arguments
max_alignment: 100
bowtie2_args: "--very-sensitive"

# Species arguments

Sc288_2m_full:

    name : "Sc288_2m"
    ref: "Sc288_2m/SC288_with_micron.fa"
    R1: "/home/sardine/Documents/reads/AC1/AC1.end1.fastq.gz"
    R2: "/home/sardine/Documents/reads/AC1/AC1.end2.fastq.gz"
    circular: ["plasmid_p2-micron", "chrM"]
    enzymes : ["DpnII", "HinfI"]
    sampling_rate: 1.0
    res: 2000

Sc288_2m_no_d1d2:

    name : "Sc288_2m"
    ref: "Sc288_2m/SC288_with_micron.fa"
    R1: "/home/sardine/Documents/reads/AC1/AC1.end1.fastq.gz"
    R2: "/home/sardine/Documents/reads/AC1/AC1.end2.fastq.gz"
    circular: ["plasmid_p2-micron", "chrM"]
    enzymes : ["DpnII", "HinfI"]
    sampling_rate: 1.0

    res: 2000

Sc288_2m_density_only:

    name : "Sc288_2m"
    ref: "Sc288_2m/SC288_with_micron.fa"
    R1: "/home/sardine/Documents/reads/AC1/AC1.end1.fastq.gz"
    R2: "/home/sardine/Documents/reads/AC1/AC1.end2.fastq.gz"
    circular: ["plasmid_p2-micron", "chrM"]
    enzymes : ["DpnII", "HinfI"]
    sampling_rate: 1.0
    res: 2000

Sc288_2m_no_density_no_d1d2:

    name : "Sc288_2m"
    ref: "Sc288_2m/SC288_with_micron.fa"
    R1: "/home/sardine/Documents/reads/AC1/AC1.end1.fastq.gz"
    R2: "/home/sardine/Documents/reads/AC1/AC1.end2.fastq.gz"
    circular: ["plasmid_p2-micron", "chrM"]
    enzymes : ["DpnII", "HinfI"]
    sampling_rate: 1.0
    res: 2000

Sc288_2m_no_density:

    name : "Sc288_2m"
    ref: "Sc288_2m/SC288_with_micron.fa"
    R1: "/home/sardine/Documents/reads/AC1/AC1.end1.fastq.gz"
    R2: "/home/sardine/Documents/reads/AC1/AC1.end2.fastq.gz"
    circular: ["plasmid_p2-micron", "chrM"]
    enzymes : ["DpnII", "HinfI"]
    sampling_rate: 1.0
    res: 2000

CC336:
    name : "CC336"
    ref: "e_coli/ecoli_k12_mg1655.fa"
    R1 : "/home/sardine/Documents/reads/CC336/CC336_nxq_R1_sub.fq"
    R2 : "/home/sardine/Documents/reads/CC336/CC336_nxq_R2_sub.fq"
    circular: ["NC-000913.3"]
    enzymes : ["DpnII", "HinfI"]
    sampling_rate: 0.3
    res: 2000
