samples: "config/samples.csv"
base_dir: "/pasteur/zeus/projets/p02/rsg_fast/sgradit"
out_dir: "results"
tmp_dir: "tmp"
ref_dir: "genomes/"
fastq_dir: "reads/"

threads: 64
threads_small: 32
threads_big : 128

# Alignment arguments
max_alignment: 100
bowtie2_args: "--very-sensitive"

# Contatc map arguments
balance_args: "--mad-max 10 --min-nnz 5"
cmap: Reds
zoom_width: 32000


# Species arguments
Sc288:
    name : "Sc288"
    ref: "Sc288/SC288_with_micron.fa"
    annotation: ""
    circular: ["plasmid_p2-micron", "chrM"]
    enzyme : ["DpnII", "HinfI"]
    sampling_rate: 0.5
    rounds : 10
    magnitude : 0.8
    mode: "full"
    res: 2000

# Species arguments
E_coli:
    name : "CC336"
    ref: "/home/sardine/Documents/genomes/e_coli/ecoli_k12_mg1655.fa"
    annotation: ""
    circular: ["NC-000913.3"]
    enzyme : ["DpnII", "HinfI"]
    sampling_rate: 0.3
    rounds : 10
    magnitude : 0.8
    mode: "full"
    res: 2000


# # Species arguments
# P_falciparum:
#     name : "P_falciparum"
#     ref: "p_flaciparum/PlasmoDB-55_Pfalciparum3D7_Genome_w_mit_api.fasta"
#     annotation: ""
#     circular: ["Pf3D7_MIT_v3", "Pf3D7_API_v3"]
#     enzyme : ["MboI"]
#     sampling_rate: 0.3
#     rounds : 10
#     magnitude : 0.8
#     mode: "full"
#     res: 10000