name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -v -Ur requirements.txt
        pip install codecov nose2 nose
        pip install -e .

    - name: Check installed package (hicberg)
      run: hicberg --version

    - name: Check installed package (cooler)
      run: cooler --version

    - name: Lint and test
      run: |
        pip install pytest-pylint pytest pytest-cov pylint codecov mappy
        pytest -x --pylint --pylint-error-types=EF --pylint-rcfile=.pylintrc --doctest-modules --doctest-modules hicberg
        pytest -x --cov=hicberg
        codecov