name: build

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Create micromamba env. for package
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: hicberg.yaml
    - name: Install package
      run: |
        micromamba install -y -n hicberg --file hicberg.yaml
        micromamba run -n hicberg pip install .
    - name: Check installed package (hicberg)
      run: |
        micromamba run -n hicberg hicberg --version
    - name: Check installed package (cooler) 
      run: |
        micromamba run -n hicberg cooler --version
    - name: Lint and test
      run: |
        micromamba run -n hicberg pip install pytest-pylint pytest pytest-cov pylint codecov mappy
        micromamba run -n hicberg pytest -x --pylint --pylint-error-types=EF --pylint-rcfile=.pylintrc --doctest-modules --doctest-modules hicberg
        micromamba run -n hicberg pytest -x --cov=hicberg
        micromamba run -n hicberg codecov