name: build

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:

    - name: Checkout repo
      uses: actions/checkout@v2
    
    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        environment-file: hicberg.yaml
        activate-environment: hicberg 

    - name: Install package
      run: |
        pip install .
      shell: bash -l {0} 

    - name: Check installed package (hicberg)
      run: hicberg --version

    - name: Check installed package (cooler)
      run: cooler --version

    - name: Lint and test
      run: |
        pip install pytest-pylint pytest pytest-cov pylint codecov mappy
        pytest -x --pylint --pylint-error-types=EF --pylint-rcfile=.pylintrc --doctest-modules --doctest-modules hicberg
        pytest -x --cov=hicberg
        codecov